<html>
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" type="text/css" href="style.css">
    </head>
    <body>
    <div class="dropdown">
        <button class="dropdown-btn">Gerenciamentos de salas</button>
        <div class="dropdown-content">
            <button class="dropdown-option" onclick="window.location.href='incluirsalas.php'">Incluir Salas</button>
            <button class="dropdown-option" onclick="window.location.href='alterarsala.php'">Alterar Salas</button>
        </div>

</div>

  <div class="dropdown">
        <button class="dropdown-btn">Gerenciamentos de funcionarios</button>
        <div class="dropdown-content">
            <button class="dropdown-option" onclick="window.location.href='alterarfunc.php'">Alterar Funcionarios</button>
        </div>
</div>

<div class="dropdown">
        <button class="dropdown-btn">Gerenciamento inventario</button>
        <div class="dropdown-content">
            <button class="dropdown-option" onclick="window.location.href='incluirequip.php'">Incluir equipamento</button>
            <button class="dropdown-option" onclick="window.location.href='alterarequip.php'">Alterar Equipamento</button>
        </div>
</div>