<head>
    <link rel="Website Icon" type="png"href="inden.png">
    <link rel="stylesheet" href="stylec.css">
</head>
        <section class="cabecalho">
            <nav>
            <center>
                <label class="logo">
                    <img class="logo-img" src="logo.png">
                </label>
                </center>
                <span class="logou-btn">
                <button  class="return-btn" onclick="window.location.href='logout.php'">Logout</button>
                </span>
            </nav>      
        </section>
                
    </header>