<html>
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" type="text/css" href="stylemen.css">

     </head>
    <body>
    <center>
    <div class="menu">
        
         <details onmouseover="this.open=true" onmouseout="this.open=false" >
            <summary><b class="men">Menu</b></summary>
        <div class="linha">
        <button class="int"><a href="fsolicitacao.php">Gerenciamentos </a></buttom>
        <button class="int"><a href="mostrafuncadm.php">Funcionarios</a></buttom>
        <button class="int"><a href="mapaadm.php">Mapa</a></button>
        <button class="int"><a href="mostrainvadm.php">Inventario</a></button>
        </div>
        </details>
    </div>
    </center>
    </body>
</html>