<html>
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" type="text/css" href="stylemen.css">

     </head>
    <body>
    <center>
    <div class="menu">
        
         <details onmouseover="this.open=true" onmouseout="this.open=false" >
            <summary><b class="men">- - -</b></summary>
        <div class="linha">
        <button class="int"><a href="mostrafunc.php">Funcionarios</a></buttom>
        <button class="int"><a href="mostrainv.php">Inventario</a></buttom>
        <button class="int"><a href="mapa.php">Mapa </a></button>
        </div>
        </details>
    </div>
    </center>
    </body>
</html>