<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="styler.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
  <footer>
  <div class="container">
                <p class="descript"> Todos os direitos resevados!
                    <br>
                    © | 2023 | Equipe CoreForce
                    <br>
                </p>
        
            </footer>      
 </body>           